# Generated by Django 4.1.7 on 2023-03-25 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=gallery.models.user_directory_path)),
                ('file_type', models.CharField(default='image', max_length=7)),
                ('likers', models.ManyToManyField(related_name='scrap_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=models.SET(gallery.models.get_sentinel_user), related_name='scraps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='gallery.scrap')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('likers', models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gallery.comment')),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.scrap')),
                ('user', models.ForeignKey(on_delete=models.SET(gallery.models.get_sentinel_user), related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'scrap'), name='unique_scrap_tag_combination'),
        ),
    ]
