# Generated by Django 4.1.7 on 2023-03-25 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_picture_path)),
            ],
        ),
    ]
